version: "3.8"

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - "8761:8761"
    networks:
      - hazmela-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8761 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10


  edge-server:
    build: ./edge-server
    container_name: edge-server
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SERVER_SSL_KEY_STORE=file:/keystore/edge.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=password
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    volumes:
      - ./edge-server/keystore:/keystore
    ports:
      - "8081:8081"
    networks:
      - hazmela-net


  # Servicios del microservicio de usuarios
  db-user:
    image: postgres:15
    container_name: db-user
    environment:
      POSTGRES_DB: ms_user_hazmelaucb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5432:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
      - ./ms-user/dbUser.sql:/docker-entrypoint-initdb.d/dbUser.sql
    networks:
      - hazmela-net
    depends_on:
      - config-server

  ms-user:
    build: ./ms-user
    container_name: ms-user
    depends_on:
      - db-user
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-user:5432/ms_user_hazmelaucb_db
      - SPRING_DATASOURCE_USERNAME=postgres
      #- SPRING_DATASOURCE_PASSWORD=1590PP
    ports:
      - "7002:7002"
    networks:
      - hazmela-net

  # Servicios del microservicio de autenticaci√≥n
  db-auth:
    image: postgres:15
    container_name: db-auth
    environment:
      POSTGRES_DB: ms_auth_hazmelaucb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5434:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
      - ./ms_authenticate/dbAuth.sql:/docker-entrypoint-initdb.d/dbAuth.sql
    networks:
      - hazmela-net
    depends_on:
      - config-server

  ms-auth:
    build: ./ms_authenticate
    container_name: ms-auth
    depends_on:
      - db-auth
      - eureka-server
      - config-server
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5432/ms_auth_hazmelaucb_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1590PPL
    ports:
      - "7001:7001"
    networks:
      - hazmela-net

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f -u ${CONFIG_SERVER_USR}:${CONFIG_SERVER_PWD} http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      - hazmela-net

volumes:
  pgdata_user:
  pgdata_anuncios:
  pgdata_auth:
  pgdata_rating:


networks:
  hazmela-net:
    driver: bridge
