version: '3.8'

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hazmela-net

  edge-server:
    build: ./edge-server
    container_name: edge-server
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - hazmela-net


  # Servicios del microservicio de usuarios
  db-user:
    image: postgres:15
    container_name: db-user
    environment:
      POSTGRES_DB: ms_user_hazmelaucb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5432:5432"
    volumes:
      - pgdata_user:/var/lib/postgresql/data
      - ./ms-user/dbUser.sql:/docker-entrypoint-initdb.d/dbUser.sql
    networks:
      - hazmela-net

  ms-user:
    build: ./ms-user
    container_name: ms-user
    depends_on:
      - db-user
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/ms_user_hazmelaucb_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590PPL
    ports:
      - "7002:7002"
    networks:
      - hazmela-net

  # Servicios del microservicio de autenticaci√≥n
  db-auth:
    image: postgres:15
    container_name: db-auth
    environment:
      POSTGRES_DB: ms_auth_hazmelaucb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5434:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
      - ./ms_authenticate/dbAuth.sql:/docker-entrypoint-initdb.d/dbAuth.sql
    networks:
      - hazmela-net

  ms-auth:
    build: ./ms_authenticate
    container_name: ms-auth
    depends_on:
      - db-auth
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-auth:5432/ms_auth_hazmelaucb_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590PPL
    ports:
      - "7001:7001"
    networks:
      - hazmela-net

  # Servicios del microservicio de anuncios
  db-anuncios:
    image: postgres:15
    container_name: db-anuncios
    environment:
      POSTGRES_DB: anuncios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5433:5432"  # Cambiado a puerto 5433 externo para evitar conflicto
    volumes:
      - pgdata_anuncios:/var/lib/postgresql/data
      - ./ms_anuncios/dbAnuncios.sql:/docker-entrypoint-initdb.d/dbAnuncios.sql
    networks:
      - hazmela-net

  ms-anuncios:
    build: ./ms_anuncios
    container_name: ms-anuncios
    depends_on:
      - db-anuncios
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-anuncios:5432/anuncios_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590PPL
    ports:
      - "7005:7005"
    networks:
      - hazmela-net

volumes:
  pgdata_user:
  pgdata_anuncios:
  pgdata_auth:

networks:
  hazmela-net:
    driver: bridge