springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: "com.hazmelaucb.ms_authenticate"
  paths-to-match: "/**"

api:
  common:
    version: 1.0.0
    title: API de Intentos de Inicio de Sesión
    description: Servicio para registrar y visualizar intentos de inicio de sesión en HazmelaUCB
    termsOfService: https://www.hazmelaucb.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.hazmelaucb.com/wiki
    contact:
      name: Soporte HazmeLaUCB
      url: https://www.hazmelaucb.com/contacto
      email: soporte@hazmelaucb.com

  responseCodes:
    ok.description: OK, operación exitosa.
    badRequest.description: Solicitud incorrecta o datos inválidos.
    notFound.description: No se encontró el recurso solicitado.

  loginAttempt:
    get:
      description: Obtiene los intentos de inicio de sesión de un usuario por su ID.
      notes: |
        # Respuesta exitosa
        - Devuelve una lista con los intentos de inicio de sesión ordenados por fecha.

        # Respuestas con error
        1. Si el ID del usuario no es válido, retorna **400 - Bad Request**.
        2. Si el usuario no existe, retorna **404 - Not Found**.
