springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: "com.hazmelaucb.ms_authenticate"
  paths-to-match: "/**"

api:
  common:
    version: 1.0.0
    title: API de Administración de Usuarios
    description: Servicio para la gestión de usuarios bloqueados en HazmelaUCB
    termsOfService: https://www.hazmelaucb.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.hazmelaucb.com/wiki
    contact:
      name: Soporte HazmeLaUCB
      url: https://www.hazmelaucb.com/contacto
      email: soporte@hazmelaucb.com

  responseCodes:
    ok.description: OK, operación exitosa.
    notFound.description: No se encontró el usuario con el correo especificado.

  admin:
    unlockUser:
      description: Desbloquea la cuenta de un usuario restableciendo sus intentos fallidos de inicio de sesión.
      notes: |
        # Respuesta exitosa
        - Confirma que el usuario ha sido desbloqueado correctamente.

        # Respuestas con error
        1. Si el usuario no existe, retorna **404 - Not Found**.
