server:
  port: ${SERVER_PORT:7005}

spring:
  application:
    name: ms-anuncios
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    #url: jdbc:postgresql://localhost:5432/anuncios_db
    #username: postgres
    #password: 1590PPL
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - "classpath:application-openapi-anuncio.yml"
      - "classpath:application-openapi-tag.yml"

app.eureka-server: eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5