server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-anuncios
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/anuncios_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:yourpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:
      - "classpath:application-openapi-anuncio.yml"
      - "classpath:application-openapi-tag.yml"
  profiles:
    include:
      - openapi-anuncio
      - openapi-tag

app.eureka-server: ${EUREKA_SERVER:eureka-server}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# Aquí podemos incluir configuración adicional para unificar ambas APIs
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

  group-configs:
    - group: anuncios
      paths-to-match: /api/anuncios/**
      packages-to-scan: com.hazmelaucb.ms_anuncios.controller
    - group: tags
      paths-to-match: /api/tags/**
      packages-to-scan: com.hazmelaucb.ms_anuncios.controller

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
