version: '3.8'

services:

  # Eliminado eureka-server y edge-server para pruebas locales
  # eureka-server:
  #   build: ../eureka-server
  #   container_name: eureka-server
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - hazmela-net

  # edge-server:
  #   build: ../edge-server
  #   container_name: edge-server
  #   depends_on:
  #     - eureka-server
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - hazmela-net

  db-report:
    image: postgres:15
    container_name: db-report
    environment:
      POSTGRES_DB: ms_report_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1590PPL
    ports:
      - "5432:5432"
    volumes:
      - pgdata_report:/var/lib/postgresql/data
    networks:
      - hazmela-net

  ms-report:
    build:
      context: .
    container_name: ms-report
    depends_on:
      - db-report
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-report:5432/ms_report_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590PPL
    ports:
      - "7006:7006"
    networks:
      - hazmela-net

volumes:
  pgdata_report:

networks:
  hazmela-net:
    driver: bridge