version: '3.8'

services:
  ms-report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-report
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reportdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ms-report-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: