version: '3.8'

services:
  ms-report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-report
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db-report
      - eureka-server

  db-report:
    image: postgres:13
    container_name: ms-report-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-report
    volumes:
      - db_data:/var/lib/postgresql/data

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761

volumes:
  db_data:
