version: '3.8'

services:
  db-user:
    image: postgres:15
    container_name: db-user
    environment:
      POSTGRES_DB: ms_user_hazmelaucb_db   # Nombre de la BD
      POSTGRES_USER: postgres              # Usuario de la BD
      POSTGRES_PASSWORD: 1590PPL           # Contraseña de la BD
    ports:
      - "5432:5432"
    networks:
      - user-net
    volumes:
      - pgdata:/var/lib/postgresql/data    # Persiste datos aunque reinicies

  ms-user:
    build: .                               # Construye usando tu Dockerfile local
    container_name: ms-user
    depends_on:
      - db-user                            # Espera que PostgreSQL esté listo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-user:5432/ms_user_hazmelaucb_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1590PPL
    ports:
      - "7002:7002"                        # Puerto local : puerto interno
    networks:
      - user-net

volumes:
  pgdata:

networks:
  user-net:
    driver: bridge
