server:
  port: 7001

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    org.springdoc: DEBUG



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-rarting-db
    username: postgres
    password: 123fuser1442
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: user
      password: password
    enabled: false  # ðŸ”¥ Desactiva la autenticaciÃ³n en toda la app

  config:
    import:
      - "classpath:application-openapi-rating.yml"
