server:
  port: 7001

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    org.springdoc: DEBUG



spring:
  datasource:
    url: jdbc:postgresql://database:5432/msratingdb
    username: msrating_user
    password: msrating_password
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: user
      password: password
    enabled: false  # ðŸ”¥ Desactiva la autenticaciÃ³n en toda la app

  config:
    import:
      - "classpath:application-openapi-rating.yml"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
