server:
  port: 7002

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    #url: jdbc:postgresql://localhost:5432/ms_user_hazmelaucb_db
    #username: postgres
    #password: 1590PPL
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - "classpath:application-openapi-admin.yml"
      - "classpath:application-openapi-student.yml"
      - "classpath:application-openapi-user.yml"
