spring.application.name: config-server
server.port: 8888

spring.cloud.config.server.git:
  uri: https://github.com/MaxPastenL/UCB-SIS-313_config_server.git
  default-label: main  # o master, o cualquier branch
  #search-paths: config  # opcional, si los yml estï¿½n en una carpeta
  username: Max-APL
  password: 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 #Token generado en github
  timeout: 30
  force-pull: true

spring.security:
  user:
    name: ${CONFIG_SERVER_USR:config-usr}
    password: ${CONFIG_SERVER_PWD:SIS313ucb}

  # WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
  management.endpoint.health.show-details: "ALWAYS"
  management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.config: DEBUG
    #    org.eclipse.jgit: DEBUG

encrypt.key: mySecretKey

---
spring.config.activate.on-profile: docker