version: "3.8"

services:
  msrating:
    build: .
    container_name: msrating-service
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/ms-rarting-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123fuser1442
    networks:
      - msrating_network

  database:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ms-rarting-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123fuser1442
    networks:
      - msrating_network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  msrating_network:

volumes:
  pgdata:
