version: "3.8"

services:
  msrating:
    build: .
    container_name: msrating-service
    ports:
      - "5008:5008"
    depends_on:
      - database
      - eurekaserver
    environment:
      - SERVER_PORT=5008
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-rating:5432/ms-rating-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123fuser1442
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - APP_EUREKA-SERVER=eureka-server
    networks:
      - hazmela-net

  database:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ms-rating-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123fuser1442
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - hazmela-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  eurekaserver:
    image: hazmela-backend-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - hazmela-net

volumes:
  pgdata:
